jpaver/opengametools

- src/ogt_vox.h
Previously `_vox_str_scanf` was defined as `scanf` for non-windows OSes, as a result, loading a vox file under Linux would cause the program to hang waiting for user input on stdin. Changed to `sscanf` to scan string as originally intended.
> Corrected scanf function for unixes to sscanf

- src/ogt_vox.h
Hi!
Great library, thanks for making it! It's extremely useful :)
Currently, all instances under a group will have the name of that group, instead of their own name.
For instance here, all the instances would be named `group`:
This fixes that to use the instance own name if available instead.
Note that I haven't thoroughly tested that fix :)
> Fix instance names

- src/ogt_vox.h
on windows in debug compilation, the value will be 0xCDCD, so it needs setting.
Great lib, btw. Thanks!
> initializing variable

- src/ogt_vox.h
The `CHUNK_ID_MATL` appears to be the current approach for extended material information in MagicaVoxel, with `CHUNK_ID_MATT` being obsolete - the former is present in all .vox files exported currently, but not the later.
I have added initial support for reading this chunk in this PR, which is intended primarily as a discussion for the implementation approach prior to my making any changes along with adding support for writing these values back.
An alternative approach might be to keep the material data as a dictionary of parameters - the size of the smallest dict for each material (default diffuse) is 36bytes, and the current structure is 64 bytes, so if most materials are diffuse using dicts might be a small saving in space.
> ogt_vox: added initial support for CHUNK_ID_MATL

- src/ogt_vox.h
In `find_closest_color_in_palette` `best_score` is declared as int32_t. It's value is always `<UINT32_MAX` and assertion will always succeed(even in bad situations when `bad_score` is `INT32_MAX`). As I understand from code `best_score` should be compared to `INT32_MAX` not `UINT32_MAX`.
> Fix assertion

- src/ogt_vox.h
Building with MSVS 2019, the following warnings were being generated:
1. `ogt_vox.h(873, 31): [C4245] 'argument': conversion from 'int' to 'const T', signed/unsigned mismatch`
2. `ogt_vox.h(1504, 111): [C4244] 'return': conversion from 'uint32_t' to 'uint8_t', possible loss of data`
> Fix two compiler warnings in ogt_vox.h

- src/ogt_vox.h
The string arrays in ogt_vox are 64 bytes long, but I have encountered a string name of 64bytes plus the NULL terminator making 65 bytes.
This PR updates the size of the char arrays to 65 bytes to resolve this issue.
> VOX string size max of 64 does not include null, need 65 bytes

- src/ogt_vox.h
Running ogt_voxel through address sanitizer in our test suite gave me a hit on some potential buffer overruns, so here's a commit fixing that and some other ones I found through inspection, and also initialize a few variables we read into since the read method might leave them uninitialized.
> Fix some heap overruns & uninitialized variables that are read into

- src/ogt_voxel_meshify.h
The PR as promised. :)
Technically, we could likely remove the color from the structure, if we want it more lightweight, as returning the index allows retrieving the color from the palette. Let me know if you want me to make this change too.
> Add the palette index to the vertex structure returned by the mesh generators

- src/ogt_vox.h
the _type dict entry wasn't counted for the header of the dict
> ogt_vox: fixed MATL chunk saving

- src/ogt_vox.h
Discovered that during vox file loading resize was being called with ```count+1```, with capacity only being increased by 1 each time leading to very slow file reading for vox files with lots of models & instances - one file with many tens of thousands of such was taking over a half hour to load (I cancelled!), whereas after this optimization it took 18 seconds (including converting to my octree format in Avoyd).
This PR changes the resize to use the same approach you use elsewhere to avoid too many resizing calls.
> _vox_array::resize optimization - grow by at least 1.5x

- src/ogt_vox.h
- flattened transform was being computed correctly, it just wasn't being assigned onto the output instance. 
- the net effect was that output instances were continuing using the group relative transform rather than the flattened transform.
> ogt_vox: fix regression/bug with instance transforms not being correctly flattened when not importing groups

- src/ogt_vox.h
This seems to work on a number of import tests I've done locally. @mgerhardy @dougbinks please take a look and let me know if this works okay within your codebases too. Thanks!
There is a small API incompatibility if you already grabbed the initial animation support -- I've wrapped animations into their own structs instead of having keyframes+count embedded within instances/groups, but it should be a fairly straightforward thing to fix up.
Please let me know if you have any additional thoughts before I merge. Will try do so early next week, thanks!
> ogt_vox : implement animation looping and sampling

- src/ogt_vox.h
Add the materials of the scenes into the merge scene in ogt_vox_merge_scenes. I added the materials when the color of the master palette is added in previous update_master_palette_from_scene funtion
#38 
PS: this is my first PR 🙂
> ogt_vox: Merge materials

- src/ogt_vox.h
This PR implements the ability to switch the default endianness for ogt_vox from little endian to big endian
For SDL users, this could e.g. look like this:
```c
#include <SDL_endian.h>
#define OGT_VOX_BIGENDIAN_SWAP32  SDL_SwapLE32
#define OGT_VOX_IMPLEMENTATION
#include "external/ogt_vox.h"
```
Runtime detection example by jpaver:
```c
inline bool is_big_endian()
{
union {
uint32_t u32;
uint8_t  u8[4];
} u;
u.u32 = 0x01020304;
return u.u8[0] == 0x01;
}
inline uint32_t byte_swap_if_big_endian_32(uint32_t x)
{
return is_big_endian() ? __builtin_swap32(x) : x;
}
#define OGT_VOX_BIGENDIAN_SWAP32(x) byte_swap_if_big_endian_32(x)
```
> ogt_vox: implemented endian handling

- src/ogt_vox.h
This PR adds a check for potential buffer_size  and chunk size overflow, exiting and returning NULL if this would occur.
This prevents a corrupt .vox file from being generated, which is possible even within the MagicaVoxel 2kx1kx2k visible scene limitations.
> ogt_vox:  added check for buffer and chunk size overflow

- src/ogt_vox.h
Currently ogt_vox.h will assert on loading a model with 0 size when reading the `CHUNK_ID_XYZI` at line:
1320 `ogt_assert(size_x && size_y && size_z, "expected a SIZE chunk before XYZI chunk");`
https://github.com/jpaver/opengametools/blob/master/src/ogt_vox.h#L1320
This can be a little confusing, as the actual error can be due to the model having zero size. In addition I discovered this by saving out a .vox file with a model of zero size, so here I have also added an assert for this case in the write code.
Whilst MV appears to handle loading a 0 size model you can't create one using it's UI, so it's likely still good practice to assert on this.
> Added asserts to catch saving and loading of a model with zero size

- src/ogt_vox.h
This PR adds a progress callback with implementation in ogt_vox_write_scene and ogt_vox_read_scene*.
The current implementation works well for my own test cases in Avoyd. The ogt_vox_read_scene implementation could be improved slightly by adding more steps to the post processing after file reading but this did not take sufficient time to be visible in my testing.
> ogt_vox: added progress callback

- apps/vox2obj.cpp
- src/ogt_vox.h
fixes: https://github.com/jpaver/opengametools/issues/55
- legacy vox files don't contain information about groups, transforms, animations etc, so a lot of the paths in vox2obj that assume that groups/keyframes exist were problematic.
- we fix this in 2 ways
1. we now create a default group when importing these legacy vox files.
2. we now don't allow clients to sample directly from the ogt_vox_anim_transform structures, but only directly from the instances or the groups themselves. This allows the sampling functions to fallback to the embedded transform if no keyframes exist.
- we now expose global and local versions of transform sampling for both instances and groups. Global = world space flattened transform. Local = transform relative to the parent group.
- I took the opportunity to …
> opengametools: fix vox2obj reading + converting legacy .vox files

- .github/workflows/main.yml
- .gitignore
- CMakeLists.txt
- demo/demo_vox.cpp
- src/ogt_vox.h
I've added a very basic cmake script to perform the cl.exe search - I'm not very familiar with windows and could find an easy way to find cl.exe.
I've also added a test case in form of the demo_vox application to the pipeline.
The build artifacts are attached to each pipeline run.
see https://github.com/jpaver/opengametools/actions/runs/5637436975
> CI: added windows and osx builds as well as tests to the github pipelines

- src/ogt_vox.h
Fix for _vox_models_are_equal comparing two models with the same volume but different dimensions as equal.
In the model I had there were two pieces, one 4x9x4 and one 2x18x4 both filled with the same material. These were incorrectly detected as the same and the 2x18x4 used for both.
> Fix for _vox_models_are_equal comparing two models with the same volume

- src/ogt_vox.h
- attempted fix for https://github.com/jpaver/opengametools/issues/62. 
- we now use a new _vox_suballoc_array type that internally aligns base offset to the size of the type by default (in cases where alignment matters, I'd expect the struct to be padded to the natural alignment and for all members to have appropriate alignment padding for them too)
- this still relies upon a reasonable alignment from _vox_malloc, which should either be guaranteed to be 8 or 16 in most 64-bit platforms
@mgerhardy, PTAL and confirm this fixes your ASAN testing issue. Thanks!
> ogt_vox: add type-based memory alignment within the internal sub allocator

- src/ogt_vox.h
The camera radius property (called "Zoom" in MagicaVoxel) was loaded incorrectly from the angle_string variable. In addition it's a floating point value (and not an integer).
> Fixed camera radius reading and changed type to float

- src/ogt_vox.h
ior is ri - 1.0 (according to VOX4U (unreal 5 plugin)
some of the found values in existing vox files:
key: _ri, value: 1.01
key: _ri, value: 1.02
key: _ri, value: 1.03
key: _ri, value: 1.04
key: _ri, value: 1.09
key: _ri, value: 1.16
key: _ri, value: 1.2
key: _ri, value: 1.3
key: _ri, value: 1.33
key: _ri, value: 1.48
key: _ri, value: 1.52
key: _ri, value: 1.53
key: _ri, value: 1.66
key: _ri, value: 1.71
key: _ri, value: 1.82
key: _ri, value: 1.94
key: _ri, value: 2
key: _ri, value: 2.17
key: _ri, value: 2.33
> ogt_vox: added _ri material support

- src/ogt_vox.h
I am not sure if I am interpreting the values correctly and feedback would be welcome.
> RFC: ogt_vox: added helper function ogt_vox_camera_to_transform

- src/ogt_vox.h
This library must be compiled as C++. This comment in the src confused me for a few minutes so thought I'd submit a PR to rectify it.
> Correct comment that mistakenly suggests this library works compiled as C

- src/ogt_vox.h
I've encountered a number of vox files which were corrupt with voxels outside the bounds of the model size. This results in the voxel array bounds being overwritten when loaded.
There's already an assert in the code, but this PR adds the same test to adding the voxel data to the array. I've been able to recover some data from models which otherwise would not load with this addition and I don't think the performance hit is significant.
> CHUNK_ID_XYZI voxel bounds check to improve handling of corrupt files
